services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: severynsor_db
      POSTGRES_USER: severynsor_user
      POSTGRES_PASSWORD: severynsor_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
  
  worker:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data:
