# Generated by Django 5.2.12 on 2026-04-03 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'permissions': [('can_view_token', 'Can view and edit sensor token')]},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
