# Generated by Django 5.2.12 on 2026-04-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0003_sensorretriever_openmeteoretriever'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openmeteoretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensorretriever',
            options={},
        ),
    ]
