# Generated by Django 5.2.12 on 2026-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0004_alter_openmeteoretriever_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmeteoretriever',
            name='current_type',
            field=models.CharField(choices=[('temperature_2m', 'Temperature (2m)'), ('relative_humidity_2m', 'Relative Humidity (2m)'), ('apparent_temperature', 'Apparent Temperature'), ('precipitation', 'Precipitation'), ('wind_speed_10m', 'Wind Speed (10m)')], default='temperature_2m', max_length=50),
        ),
        migrations.AddField(
            model_name='sensorretriever',
            name='name',
            field=models.CharField(blank=True, help_text='Optional custom name for this retriever', max_length=255),
        ),
    ]
