# Generated by Django 5.2.12 on 2026-04-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0005_openmeteoretriever_current_type_sensorretriever_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherMapRetriever',
            fields=[
                ('sensorretriever_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.sensorretriever')),
                ('api_key', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('measurement_type', models.CharField(choices=[('air_pollution.aqi', 'Air Quality Index (AQI)'), ('air_pollution.pm2_5', 'PM2.5'), ('air_pollution.pm10', 'PM10'), ('air_pollution.co', 'Carbon Monoxide (CO)'), ('air_pollution.no2', 'Nitrogen Dioxide (NO2)'), ('weather.temp', 'Temperature (Celsius)'), ('weather.humidity', 'Humidity (%)'), ('weather.pressure', 'Pressure (hPa)'), ('weather.wind_speed', 'Wind Speed (m/s)')], default='air_pollution.aqi', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.sensorretriever',),
        ),
    ]
