# Generated by Django 5.2.12 on 2026-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0006_openweathermapretriever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorretriever',
            name='name',
            field=models.CharField(blank=True, help_text='Optional custom name for this retriever', max_length=255, null=True, unique=True),
        ),
    ]
