# Generated by Django 5.2.12 on 2026-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0007_alter_sensorretriever_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorretriever',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
