# Generated by Django 5.2.12 on 2026-04-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('severynsor', '0008_sensorretriever_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.sensor',),
        ),
        migrations.CreateModel(
            name='RTSPRetriever',
            fields=[
                ('sensorretriever_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.sensorretriever')),
                ('rtsp_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.sensorretriever',),
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='sensor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.record')),
                ('image', models.ImageField(blank=True, null=True, upload_to='records/')),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.record',),
        ),
        migrations.CreateModel(
            name='ValueRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.record')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='severynsor.sensor'),
        ),
        migrations.CreateModel(
            name='ValueSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.sensor')),
                ('measure_unit', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('severynsor.sensor',),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
