# Generated by Django 4.2.29 on 2026-04-03 22:02

from django.db import migrations, models
import django.db.models.deletion

def migrate_locations(apps, schema_editor):
    Sensor = apps.get_model('severynsor', 'Sensor')
    Location = apps.get_model('severynsor', 'Location')
    for sensor in Sensor.objects.all():
        loc_name = sensor.location_backup or "Unknown Location"
        loc, _ = Location.objects.get_or_create(name=loc_name, defaults={'latitude': 0.0, 'longitude': 0.0})
        sensor.location = loc
        sensor.save()

class Migration(migrations.Migration):

    dependencies = [
        ("severynsor", "0009_record_imagesensor_rtspretriever_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(name="imagerecord", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="imagesensor", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="openmeteoretriever", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="openweathermapretriever", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="rtspretriever", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="sensorretriever", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="valuerecord", options={"base_manager_name": "objects"}),
        migrations.AlterModelOptions(name="valuesensor", options={"base_manager_name": "objects"}),
        migrations.RemoveField(model_name="openmeteoretriever", name="latitude"),
        migrations.RemoveField(model_name="openmeteoretriever", name="longitude"),
        migrations.RemoveField(model_name="openweathermapretriever", name="latitude"),
        migrations.RemoveField(model_name="openweathermapretriever", name="longitude"),
        migrations.AddField(model_name="sensor", name="placement", field=models.CharField(blank=True, max_length=255, null=True)),
        migrations.RenameField(model_name="sensor", old_name="location", new_name="location_backup"),
        migrations.AddField(
            model_name="sensor",
            name="location",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="severynsor.location"),
        ),
        migrations.RunPython(migrate_locations),
        migrations.AlterField(
            model_name="sensor",
            name="location",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="severynsor.location"),
        ),
        migrations.RemoveField(model_name="sensor", name="location_backup"),
    ]
