# Generated by Django 4.2.29 on 2026-04-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("severynsor", "0010_location_alter_imagerecord_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valuesensor",
            name="measure_unit",
        ),
        migrations.AddField(
            model_name="valuesensor",
            name="measure_type",
            field=models.CharField(
                choices=[
                    ("temperature", "Temperature"),
                    ("humidity", "Humidity"),
                    ("pm25", "PM2.5"),
                    ("pm10", "PM10"),
                    ("co", "Carbon Monoxide (CO)"),
                    ("no2", "Nitrogen Dioxide (NO2)"),
                    ("pressure", "Pressure"),
                    ("wind_speed", "Wind Speed"),
                    ("aqi", "Air Quality Index (AQI)"),
                    ("precipitation", "Precipitation"),
                    ("apparent_temperature", "Apparent Temperature"),
                ],
                default="temperature",
                max_length=50,
            ),
        ),
    ]
