# Generated by Django 4.2.29 on 2026-04-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("severynsor", "0011_remove_valuesensor_measure_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openmeteoretriever",
            name="current_type",
        ),
        migrations.RemoveField(
            model_name="openweathermapretriever",
            name="measurement_type",
        ),
    ]
