# Generated by Django 5.2.12 on 2026-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0012_remove_openmeteoretriever_current_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imagesensor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='openmeteoretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='openweathermapretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rtspretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensorretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valuerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valuesensor',
            options={},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
