# Generated by Django 4.2.29 on 2026-04-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("severynsor", "0014_add_preview_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagerecord",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="imagesensor",
            options={"verbose_name": "Image", "verbose_name_plural": "Image Sensors"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["order"],
                "permissions": [("manage_dashboard", "Can manage dashboard settings")],
            },
        ),
        migrations.AlterModelOptions(
            name="openmeteoretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="openweathermapretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="rtspretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sensorretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="valuerecord",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="valuesensor",
            options={"verbose_name": "Value", "verbose_name_plural": "Value Sensors"},
        ),
    ]
