# Generated by Django 4.2.29 on 2026-04-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "severynsor",
            "0015_alter_imagerecord_options_alter_imagesensor_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDataRetriever",
            fields=[
                (
                    "sensorretriever_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="severynsor.sensorretriever",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("severynsor.sensorretriever",),
        ),
        migrations.AlterField(
            model_name="valuesensor",
            name="measure_type",
            field=models.CharField(
                choices=[
                    ("temperature", "Temperature"),
                    ("humidity", "Humidity"),
                    ("pm25", "PM2.5"),
                    ("pm10", "PM10"),
                    ("co", "Carbon Monoxide (CO)"),
                    ("no2", "Nitrogen Dioxide (NO2)"),
                    ("pressure", "Pressure"),
                    ("wind_speed", "Wind Speed"),
                    ("aqi", "Air Quality Index (AQI)"),
                    ("precipitation", "Precipitation"),
                    ("apparent_temperature", "Apparent Temperature"),
                    ("disk_used", "Disk Used"),
                ],
                default="temperature",
                max_length=50,
            ),
        ),
    ]
