# Generated by Django 5.2.12 on 2026-04-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0016_systemdataretriever_alter_valuesensor_measure_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='openmeteoretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='openweathermapretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rtspretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensorretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemdataretriever',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valuerecord',
            options={},
        ),
    ]
