# Generated by Django 4.2.30 on 2026-04-09 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("severynsor", "0017_alter_imagerecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagerecord",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="openmeteoretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="openweathermapretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="rtspretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sensorretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="systemdataretriever",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="valuerecord",
            options={"base_manager_name": "objects"},
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("retriever", "Retriever Execution"),
                            ("api_call", "API Call"),
                        ],
                        default="retriever",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "retriever",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="severynsor.sensorretriever",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="severynsor.sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
