# Generated by Django 5.2.13 on 2026-04-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0019_alter_imagerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('conditions', models.JSONField(default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='severynsor.sensor')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarms',
            },
        ),
    ]
