# Generated by Django 5.2.13 on 2026-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0021_alarm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='title',
            field=models.CharField(default='Unnamed Alarm', max_length=255),
            preserve_default=False,
        ),
    ]
