# Generated by Django 5.2.13 on 2026-04-10 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0022_alarm_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
