# Generated by Django 5.2.13 on 2026-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0023_alarm_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='send_email_when_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='send_email_when_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
