# Generated by Django 4.2.29 on 2026-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0024_alarm_send_email_when_off_alarm_send_email_when_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerecord',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='openmeteoretriever',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='openweathermapretriever',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='rtspretriever',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'permissions': [('can_view_token', 'Can view and edit sensor token'), ('can_preview_sensor', 'Can preview sensor data'), ('view_summary', 'Can view summary statistics')]},
        ),
        migrations.AlterModelOptions(
            name='sensorretriever',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='systemdataretriever',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='valuerecord',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='openweathermapretriever',
            name='api_key_new',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='rtspretriever',
            name='rtsp_url_new',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('retriever', 'Retriever Execution'), ('api_call', 'API Call'), ('live_stream', 'Live Stream')], default='retriever', max_length=20),
        ),
    ]
