# Generated by Django 4.2.29 on 2026-08-11 11:35

from django.db import migrations, models
import django.db.models.deletion
import severynsor.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('severynsor', '0027_finalize_encrypted_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapoRetriever',
            fields=[
                ('sensorretriever_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='severynsor.sensorretriever')),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address of the Tapo Hub (e.g. H100)')),
                ('username', models.CharField(help_text='Tapo account email', max_length=255)),
                ('password', severynsor.db_fields.EncryptedCharField(help_text='Tapo account password', max_length=512)),
                ('device_id', models.CharField(help_text='Device ID of the T310 or T315 sensor', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('severynsor.sensorretriever',),
        ),
    ]
